import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx}", "./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f8f9fa",
        "on-surface": "#191c1d",
        "on-surface-variant": "#45474a",
        outline: "#75777a",
        "outline-variant": "#c5c6ca",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1a1c1e",
        "on-primary-container": "#838486",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        secondary: "#4f6600",
        "secondary-container": "#bdf200",
        "secondary-fixed": "#c0f500",
        "secondary-fixed-dim": "#a8d700",
        "on-secondary-fixed": "#161f00",
        "on-secondary-container": "#526b00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#410001",
        lime: "#c8ff00",
        "lime-signal": "#C8FF00",
        coral: "#FF453A",
        cyan: "#00e5ff",
        brand: {
          green: "#84cc16",
          neon: "#22c55e",
          cracked: "#ef4444",
          dark: "#0a0a0a",
          card: "#fafafa",
          line: "#e5e7eb",
          border: "#d1d5db",
          grid: "#f3f4f6",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "pad-2xs": "4px",
        "pad-xs": "8px",
        "pad-sm": "12px",
        "pad-md": "16px",
        "pad-lg": "24px",
        "pad-xl": "32px",
        "pad-2xl": "48px",
        "pad-3xl": "64px",
        "pad-4xl": "96px",
        gutter: "24px",
        "grid-unit": "4px",
        "col-max-width": "1280px",
      },
      maxWidth: {
        "col-max-width": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-space)", "var(--font-hanken)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
        "display-hero": ["var(--font-space)", "sans-serif"],
        "display-hero-mobile": ["var(--font-space)", "sans-serif"],
        "headline-xl": ["var(--font-space)", "sans-serif"],
        "headline-xl-mobile": ["var(--font-space)", "sans-serif"],
        "headline-lg": ["var(--font-space)", "sans-serif"],
        "headline-md": ["var(--font-space)", "sans-serif"],
        "headline-sm": ["var(--font-space)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "body-sm": ["var(--font-hanken)", "sans-serif"],
        "label-code": ["var(--font-mono)", "monospace"],
        "label-status": ["var(--font-mono)", "monospace"],
        "metric-huge": ["var(--font-space)", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["64px", { lineHeight: "70px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "54px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-status": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "metric-huge": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "600" }],
      },
      boxShadow: {
        hard: "3px 3px 0px #0D0F11",
      },
    },
  },
  plugins: [],
};

export default config;
